#pragma config(Sensor, dgtl1,  bump,           sensorTouch)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           flag,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                - ADVANCED Single Joystick Control -                                *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses a single joystick, either right or left (this is configurable below) to drive   *|
|*  the robot.                                                                                        *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Ch1 is the X axis and Ch2 is the Y axis for the RIGHT joystick.                             *|
|*    2)  Ch3 is the Y axis and Ch4 is the X axis for the LEFT joystick.                              *|
|*    3)  'abs(z)' is the ABSOLUTE VALUE of 'z'.                                                      *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Motor - Port 2          rightMotor           VEX Motor           Right motor                    *|
|*    Motor - Port 3          leftMotor            VEX Motor           Left motor                     *|
\*----------------------------------------------------------------------------------------------------*/

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
task main ()
{
	int joy_x;
	int joy_y;
	int threshold = 10;
	bool shift = false;

	while(vexRT[Btn7L] == 0 && vexRT[Btn8R] == 0)
	{
		joy_x = vexRT[Ch4];
		joy_y = vexRT[Ch3];
		if(vexRT[Btn7D] == 1) {
			if(!shift)
			{
				joy_y = joy_y * -1;
			}
			shift = true;
		}
		else {shift = false;}
		// Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
		if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y > 0))
		{
			motor[leftMotor]  = (joy_y + joy_x)/2;
			motor[rightMotor] = (joy_y - joy_x)/2;
		}
		// Backwards and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is NEGATIVE)
		else if((abs(joy_x) > threshold) && (abs(joy_y) > threshold) && (joy_y < 0))
		{
			motor[leftMotor]  = (joy_y - joy_x)/2;
			motor[rightMotor] = (joy_y + joy_x)/2;
		}
		// Turning in place: (abs(X) is above the threshold, abs(Y) is below the threshold)
		else if((abs(joy_x) > threshold) && (abs(joy_y) < threshold))
		{
			motor[leftMotor]  = joy_x;
			motor[rightMotor] = (-1 * joy_x);
		}
		// Standing still: (both abs(X) and abs(Y) are below the threshold)
		else
		{
			motor[leftMotor]  = 0;
			motor[rightMotor] = 0;
		}
		if (vexRT[Btn5U] == 1 || vexRT[Btn6U])
		{
			motor[leftMotor] = 127;
			motor[rightMotor] = -127;
			wait(1);
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
		}
		if (SensorValue[bump] == 1 && vexRT[Btn5D] != 1 && vexRT[Btn6D] != 1)
		{
			motor[leftMotor] = 0;
			motor[rightMotor] = 0;
			motor[flag] = 127;
			wait(5);
			motor[flag] = 0;
		}
	}
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
