#pragma config(Motor,  port1,           frontLeft,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port2,           frontRight,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port3,           backLeft,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           backRight,     tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	// User control code here, inside the loop
	bool toggle1 = false;
	int toggletime = 150;
	bool togglecheck = false;
	int X2 = 0, Y1 = 0, X1 = 0, threshold = 10;

	while (true)
	{
		if (time1[timer1] >= toggletime)
		{
			togglecheck = true;
			clearTimer(timer1);
		}
		//Create "deadzone" variables. Adjust threshold value to increase/decrease deadzone

		//Create "deadzone" for Y1/Ch3
		if(abs(vexRT[Ch4]) > threshold)
			Y1 = vexRT[Ch4];
		else
			Y1 = 0;
		//Create "deadzone" for X1/Ch4
		if(abs(vexRT[Ch3]) > threshold)
			X1 = vexRT[Ch3];
		else
			X1 = 0;
		//Create "deadzone" for X2/Ch1
		if(abs(vexRT[Ch1]) > threshold)
			X2 = vexRT[Ch1];
		else
			X2 = 0;
		//fixed axises
		X1 = X1 * -1;
		X2 = X2 * -1;
		Y1 = Y1;

		if (togglecheck == true)
		{
			if (vexRT[Btn8D] == 1)
			{
				if (toggle1 == false)
					toggle1 = true;
				else
					if (toggle1 == true)
					toggle1 = false;
			}
		}
		if (toggle1 == true)
		{
			X1 = X1 * -1;
			Y1 = Y1 * -1;
		}


		//Remote Control Commands
		motor[frontRight] = Y1 - X2 - X1;
		motor[backRight] =  Y1 - X2 + X1;
		motor[frontLeft] = Y1 + X2 + X1;
		motor[backLeft] =  Y1 + X2 - X1;

		togglecheck = false;
	}


}
