#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  lowlift,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  midlift,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  toplift,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           leftMotor,     tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           frontMotor,    tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           rearMotor,     tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

	int X1;            // Strafe
	int Y1;            //Forward / back
	int X2;						 //Rotation
	int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
	bool toggle1 = false;  //front toggle
	bool toggle2 = false;	 //precision toggle
	int precision = 100; //precision %
	int toggletime = 150;		//how often to check for toggle (in ms)
	bool togglecheck = false; //checking for toggle this round
	clearTimer(timer1); //zeros out the timer for toggle
	precision = precision / 100;
	while(1 == 1) //loops forever
	{
		X1 = vexRT[Ch4];   //Strafe - Left X, Remote 1
		Y1 = vexRT[Ch3];   //Forward / back - Left Y, Remote 1
		X2 = vexRT[Ch1];   // Rotation - Right X, Remote 1

		if (time1[timer1] >= toggletime) //if the time on the toggle timer is greater than how often to check
		{
			togglecheck = true; //check toggles this round
			clearTimer(timer1); //reset toggle timer
		}

		if (togglecheck == true) //if checking toggle this round (put buttons to check inside this if statement)
		{
			if (vexRT[Btn8L] == 1) //check right left button
			{
				if (toggle1 == false) //if true switch toggle
					toggle1 = true;
				else
					if (toggle1 == true)
					toggle1 = false;
				if (vexRT[Btn8R] == 1) //check right right button
				{
					if (toggle2 == false) //if true switch toggle
						toggle2 = true;
					else
						if (toggle2 == true)
						toggle2 = false;
				}
			}
		}
		if (toggle1 == true) //toggled code toggle 1
		{
			X1 = X1 * -1; //invert strafe
			Y1 = Y1 * -1; //invert forward and back
		} // reasoning, if flipping the front, then rotation won't flip but other axes will

		if (toggle2 == true) //toggled code toggle 2
		{
			X1 = X1 * precision; //put each axis at X%
			X2 = X2 * precision;
			Y1 = Y1 * precision;
		}

		if (abs(X1) < threshold) //if any axes are less then the threshold, then zero them out
			X1 = 0;
		if (abs(X2) < threshold)
			X2 = 0;
		if (abs(Y1) < threshold)
			Y1 = 0;


		motor[leftMotor]  = (Y1 + X2)/2; //set standard drive train
		motor[rightMotor] = (Y1 - X2)/2;

		if (abs(X1) > abs(X2)) //set front and back wheels to the greater X
		{
			motor[frontMotor] = (X1);
			motor[rearMotor] = (X1);
		}
		else
		{
			motor[frontMotor] = (X2);
			motor[rearMotor] = (X2 * -1);
		}




		togglecheck = false; // turn off checking for toggle

	}


}
