#pragma config(Motor,  port1,           leftMotor,    tmotorNormal, openLoop)
#pragma config(Motor,  port2,           rightMotor,     tmotorNormal, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
	{
		int X1;            // will hold the X value of the analog stick (choices below)
		int Y1;            // will hold the Y value of the analog stick (choices below)
		int X2;
		int threshold = 10;   // helps to eliminate 'noise' from a joystick that isn't perfectly at (0,0)
	bool toggle1 = false;
	int toggletime = 150;
	bool togglecheck = false;
		while(1 == 1)
		{
			X1 = vexRT[Ch4];   // This is the RIGHT analog stick.  For LEFT, change 'Ch1' to 'Ch4'.
			Y1 = vexRT[Ch3];   // This is the RIGHT analog stick.  For LEFT, change 'Ch2' to 'Ch3
			X2 = vexRT[Ch1];

			if (time1[timer1] >= toggletime)
		{
			togglecheck = true;
			clearTimer(timer1);
		}

		if (togglecheck == true)
		{
			if (vexRT[Btn8D] == 1)
			{
				if (toggle1 == false)
					toggle1 = true;
				else
					if (toggle1 == true)
					toggle1 = false;
			}
		}
		if (toggle1 == true)
		{
			X1 = X1 * -1;
			Y1 = Y1 * -1;
		}
		togglecheck = false;

			if (abs(X1) < threshold)
        X1 = 0;
      if (abs(X2) < threshold)
        X2 = 0;
      if (abs(Y1) < threshold)
        Y1 = 0;

			// Forward, and swing turns: (both abs(X) and abs(Y) are above the threshold, and Y is POSITIVE)
				motor[leftMotor]  = (Y1 + X2)/2;
				motor[rightMotor] = (Y1 - X2)/2;

		}

	}
}
